from pathlib import Path

RL=False
FRAME_DURATION=120

BASE_DIR = Path(__file__).parent
RESOURCES_DIR = BASE_DIR / "resources" / "Animations"
FRAME_SIZE = 128

BASE_STAMINA_RESTORE_VALUE_PER_TICK = 1

DEFAULT_HP = 16
DEFAULT_STAMINA = 20
STAMINA_BOTTOM_LIMIT = -4
